# docker/Dockerfile
FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api ./api
COPY db ./db
COPY recommender ./recommender 

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
